### ISSUE TITLE
Migrate paths.py to config.yaml

### ISSUE THREAD

**Issue by devjiel** [devjiel/AGENT-TESTER#1]
## Context
Currently, all path configurations are hardcoded in `paths.py`. We should migrate these to a more flexible `config.yaml` file.

## Proposed Changes
1. Create `config.yaml` with path configurations:
```yaml
paths:
  data_dir: "data"
  screenshots_dir: "data/screenshots"
  analyses_dir: "data/analyses"
  interface_description_file: "data/analyses/interface_description.txt"
```

## Tasks
- [ ] Create config loader utility
- [ ] Update imports to use new config
- [ ] Add config.yaml example to README
- [ ] Remove paths.py
- [ ] Add error handling

## Benefits
- Easy configuration without code changes
- Better separation of concerns
- More flexible deployment options
- Easier testing
